### PR TITLE
Footprint update

### LINKED ISSUE #36: Build new WQP site crosswalk that depends on lake feature polygons
The existing crosswalk we use was build several years ago (new WQP sites have probably been added) 

we'll want to be able to update the WQP crosswalk if new lakes and/or new sites are added.

### LINKED ISSUE #40: update NLDAS to include expansion of the footprint

### PR DESCRIPTION
**Pull request by jread-usgs**
fixes #36 fixes #40

### CODE REVIEW

**Comment by jread-usgs** [comment]
nothing crazy in here 👀

**Comment by aappling-usgs** [comment]
Why the separate branch?

**Comment by jread-usgs** [comment]
> Why the separate branch?

mainly because I am merging my own PRs and want to open a single PR at the end to merge this branch and have the expansion in place. It probably doesn't matter, but didn't want to have this get in the way of people needing to do things w/ the existing pipeline since I knew this was going to be a long running update. Do you have a preference to keep these kinds of updates on `master`?

**Comment by aappling-usgs** [comment]
I think you have a lot of flexibility because you're the only one working on it right now. A single huge PR will probably be cleaner than the individual PRs but will also probably be too big for anybody to review meaningfully. The main consideration from a pipeline perspective is that to the extent that you alter the shared cache, teammates using those cached files should have the updated .ind and build/status ASAP. But again, since nobody else is tapping this pipeline directly right now (and pipeline 3 uses a manual system to connect to these files), I think you can choose freely whether to merge into master or a separate branch. So I was mainly asking to understand what the desired benefits of using a non-master branch would be, which you've answered above. And to make sure that you're not planning to keep everything on a separate branch indefinitely.

**Pull request merged**
