### PR TITLE
WQP pull for real

### PR DESCRIPTION
**Pull request by aappling-usgs**
This PR represents a complete pull of water temperature data available from WQP for all lakes in the feature_crosswalk (from wqp_nhdLookup.rds).

Result: 1,309,558 observations from 8587 monitoring locations in 4084 unique lakes (pulled from 22,290 candidate monitoring locations in 6003 unique candidate lakes).

To see the inventory, run:
```r
haves <- read_feather(sc_retrieve('6_temp_wqp_fetch/inout/wqp_haves.feather.ind'))
```
which is a df like this:
```r
# A tibble: 22,290 x 8
   PullFile                     PullTask             site_id   LakeNumObs MonitoringLocationIden~ SiteNumObs PullDate            ParamGroup
   <chr>                        <chr>                <chr>          <int> <chr>                        <int> <dttm>              <chr>     
 1 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-01-101             0 2018-08-20 15:47:52 temperatu~
 2 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-01-102          1056 2018-08-20 15:47:52 temperatu~
 3 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-01-201            10 2018-08-20 15:47:52 temperatu~
 4 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-100          1007 2018-08-20 15:47:52 temperatu~
 5 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-101            29 2018-08-20 15:47:52 temperatu~
 6 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-104             0 2018-08-20 15:47:52 temperatu~
 7 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-106           129 2018-08-20 15:47:52 temperatu~
 8 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-108             0 2018-08-20 15:47:52 temperatu~
 9 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-109             0 2018-08-20 15:47:52 temperatu~
10 temperature_180820154752_00~ temperature_1808201~ nhd_1101~      18214 MNPCA-27-0133-02-110             0 2018-08-20 15:47:52 temperatu~
# ... with 22,280 more rows
```

This is also fewer data files than I had (uninformedly) imagined. Just 7 of them, and probably could have been 5 or 6 if I'd done the data pull all in one batch instead of 3!
image

### CODE REVIEW

**Comment by limnoliver** [comment]
From Alison: 

> result: 1,309,558 observations from 8587 monitoring locations in 4084 unique lakes (pulled from 22,290 candidate monitoring locations in 6003 unique candidate lakes)

From Winslow et al (last pull): 

> In total across the three states, 1.58 million water temperature observations were collated representing 5,103 lakes

I'm less concerned about the number of observations - this doesn't include the LTER data yet, which is pulled in during the `temp_coop` steps. I'm more concerned about the number of lakes, with >1000 more lakes with data from Winslow et al, that I doubt will be recovered in the `temp_coop` steps. 

One possible explanation is that we're comparing at slightly different points in the "get" and "munge" process. Winslow et al notes that: 

> [...some text about filtering based on values] All temperature observations with points lacking a matching lake polygon were removed. Some observations did not correspond to simulated lakes (due to other missing metadata) so the final validation observations count used was lower than the total observations collated (Fig. 2b,d; 0.94 million matching water temp observations).

From the figures, it appears that the final dataset used to do model validation was 0.94 million obs  from 3952 lakes. This is closer to our count, and our count includes only data with sites that match to lakes. Our number will get lower when we rule out observations without depth metadata or weird values. 

This is all to say, I think our number seems right! Agree, @jread-usgs?

**Comment by limnoliver** [comment]
In building `6_temp_wqp_fetch` - I'm getting the error thrown from `require_local` 

> Error in require_local("6_temp_wqp_fetch/inout/wqp_wants.feather.ind") : 
  Missing a local copy of data_file[s]: 6_temp_wqp_fetch/inout/wqp_wants.feather. Force rebuild of the ind_files to use these locally. 

This is the intended behavior, correct @aappling-usgs? That to use the WQP data locally, I have to force a rebuild of the indicator files? I don't quite get how this is bypassed in the workflow if you **don't** need the data locally.

**Comment by aappling-usgs** [comment]
Oh, rats! Thanks for testing. I thought it would bypass, but that's an experimental approach and maybe I got it wrong. Can you tell why, or at least on which step, remake decided it needed to use `wqp_wants.feather` (and therefore needed to run `require_local` on the corresponding .ind file)?

**Comment by limnoliver** [comment]
Yes, seems to be when building `6_temp_wqp_fetch/inout/wqp_needs.feather.ind`

image

**Comment by aappling-usgs** [comment]
Well golly, my repo is trying to rebuild that one, too! I guess I didn't run the pull to completion. And apparently there's a bug because I'm getting
```
> scmake('6_temp_wqp_fetch')
Starting build at 2018-08-22 10:54:12
<  MAKE > 6_temp_wqp_fetch
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.dbf.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.prj.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.shp.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.shx.ind
[    OK ] 1_crosswalk_fetch/out/wqp_nhdLookup.rds.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_pull_partitions_archive.feather.ind
[    OK ] 1_crosswalk_fetch/out/lakes_sf.rds.ind
[    OK ] 2_crosswalk_munge/out/feature_crosswalk.rds.ind
[    OK ] wqp_want_lakes
[    OK ] wqp_want_sites
[    OK ] wqp_pull_params
[    OK ] wqp_want_variables
[    OK ] 6_temp_wqp_fetch/inout/wqp_wants.feather.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_haves.feather.ind
[ BUILD ] 6_temp_wqp_fetch/inout/wqp_needs.feather.ind                   |  wqp_calc_needs(needs_ind = "6_temp_wqp_fetch/inout/wqp_needs...
[  READ ]                                                                |  # loading packages
[ BUILD ] 6_temp_wqp_fetch/inout/wqp_inventory.feather.ind               |  inventory_wqp("6_temp_wqp_fetch/inout/wqp_inventory.feather....
Restoring previous version of 6_temp_wqp_fetch/inout/wqp_inventory.feather.ind
Error: `by` can't contain join column `ParamGroup`, `MonitoringLocationIdentifier` which is missing from LHS
Timing stopped at: 0 0.01 0.1
```
So I'd better fix that! Gimme a few minutes here.

**Comment by limnoliver** [comment]
Yep, getting that same bug downstream.

**Comment by aappling-usgs** [comment]
Did you end up rebuilding any of the other files? If so, it'd be good if you could let me know which .ind and build/status files got changed for you locally. (If not, even easier, and please don't bother retrying until I can work out the bug.)

**Comment by limnoliver** [comment]
No, I don't think I did before this. Here's a screenshot from my first build: 

image

**Comment by aappling-usgs** [comment]
OK, try that. My final scmake call just now went like this:
```
> scmake('6_temp_wqp_fetch')
Starting build at 2018-08-22 11:21:41
<  MAKE > 6_temp_wqp_fetch
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.dbf.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.prj.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.shp.ind
[    OK ] 1_crosswalk_fetch/out/lakes_shapefile.shx.ind
[    OK ] 1_crosswalk_fetch/out/wqp_nhdLookup.rds.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_pull_partitions_archive.feather.ind
[    OK ] 1_crosswalk_fetch/out/lakes_sf.rds.ind
[    OK ] 2_crosswalk_munge/out/feature_crosswalk.rds.ind
[    OK ] wqp_want_lakes
[    OK ] wqp_want_sites
[    OK ] wqp_pull_params
[    OK ] wqp_want_variables
[    OK ] 6_temp_wqp_fetch/inout/wqp_wants.feather.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_haves.feather.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_needs.feather.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_inventory.feather.ind
[    OK ] 6_temp_wqp_fetch/inout/wqp_pull_partitions.feather.ind
[ BUILD ] wqp_pull_plan                                                  |  wqp_pull_plan <- plan_wqp_pull(partitions_ind = "6_temp_wqp_...
[  READ ]                                                                |  # loading packages
WQP pull is up to date, so setting task plan to NULL
[ BUILD ] 6_temp_wqp_fetch_tasks.yml                                     |  create_wqp_pull_makefile(makefile = "6_temp_wqp_fetch_tasks....
WQP pull is up to date, so writing empty task remake file
[ BUILD ] 6_temp_wqp_fetch/log/6_temp_wqp_fetch_tasks.ind                |  loop_wqp_tasks(ind_file = "6_temp_wqp_fetch/log/6_temp_wqp_f...
WQP pull is up to date, so writing empty task .ind file
[ ----- ] 6_temp_wqp_fetch
Finished build at 2018-08-22 11:21:42
Build completed in 0.01 minutes
```

**Pull request merged**
