### PR TITLE
Update summary figure to acknowledge the digitizing work being done

### PR DESCRIPTION
**Pull request by lindsayplatt**
Holly and I wanted an easy way to let the undergraduates know which lakes to focus on finding hypso data. She sent a list of lakes that we have known hypso for and are being digitized. I included this information in the summary figure now.

Lots of data, but we still need to hunt down hypsography:
image

Lots of data, but we have hypsos being digitized:
image

Lots of data, but no hypsos in the pipeline:
image

### CODE REVIEW

**Comment by jread-usgs** [comment]
while you are in there, can you add the (n={number}) text to the legend to mimic what exists in the TOHA summary html? That info is helpful. Looks good, and my suggestion is optional if it is a pain to implement.

**Comment by lindsayplatt** [comment]
Reordered to what I thought was a more logical progression. Let me know if you'd like to see a different order:

image

**Comment by jread-usgs** [comment]
These numbers don't look quite right. 0 GLM lakes? That number should be 6.7K or so...

**Comment by lindsayplatt** [comment]
although ... just realized this is a bit sketchy with PGDL, TOHA, and GLM ...

**Comment by lindsayplatt** [comment]
It is due to the filter deciding there is not any meteo data. I think someone else will have to build after this is merged (or build and PR to my open PR) because it is looking in `7_drivers_munge/out` for files that I don't have and only someone who has built that step would have.

https://github.com/USGS-R/lake-temperature-model-prep/blob/master/8_viz/src/merge_lake_data.R#L16-L17

**Comment by jread-usgs** [comment]
ahhhhh, gotcha. Ok, I need to build

**Comment by lindsayplatt** [comment]
hold on a sec - made a tiny change that is coming

**Comment by lindsayplatt** [comment]
Ok, done

**Comment by jread-usgs** [comment]
Merged and rebuilt, looks good:

image

PR coming with the ind and build updates

**Comment by lindsayplatt** [comment]
@jread-usgs are you planning to build before or after this is merged?

**Pull request merged**
